server:
  port: 8888
#不推荐这种方式,拿到密钥就可以进行解密
jasypt:
  encryptor:
    password: ${jasypt_encryptor_password:Heyou@2020}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  datasource:
    username: ENC(t6mRCShQFA/BI0mJ9fhMzg==)
    password: ENC(J6favFnOOW00s3JbZl6xkQ==)
    url: jdbc:mysql://localhost:3306/mytest_db?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0 #Redis中默认有16个库，此处配置使用第0个库
    host: 127.0.0.1
    port: 6379
    timeout: 10000

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.heyou.springboot.entity # 注意：对应实体类的路径